### ISSUE TITLE
Checking the OperatingSystem inside TEstBase probably isn't correct

### ISSUE THREAD

**Issue by PureWeen** [jfversluis/BasicAppiumSample#1]
I don't think this code is testing the correct OS accurately

![image](https://github.com/jfversluis/BasicAppiumSample/assets/5375137/a40d375d-ef02-4d2c-ae40-b8a31959456b)

It's most likely just returning true if you're on a Mac and true if you're on a windows desktop

**Comment by jfversluis** [comment]
@PureWeen Is this functionality not working correctly in .NET MAUI then? Or am I not understanding you correctly?

This code is currently functioning properly when running the tests across all platforms.

Do you have other suggestions?

**Comment by jfversluis** [comment]
Yeah you were totally right about this one. Fixed this differently now in the new approach: https://github.com/jfversluis/BasicAppiumSample/tree/separate-projects-stable-appium
