### ISSUE TITLE
Should we move code that's actually interacting with appium to extension methods? 

### ISSUE THREAD

**Issue by PureWeen** [jfversluis/BasicAppiumSample#3]
I wonder if this code here

![image](https://github.com/jfversluis/BasicAppiumSample/assets/5375137/7f9a7687-2504-488a-9daa-31822d302824)

Should be an extension method on `AppiumDriver` opposed to being part of the base class. 

I feel like having too much on the base class is going to create a bit too much cognitive load.

**Comment by jfversluis** [comment]
My idea behind this is that this is a sample app that people will recreate for their own app and I can imagine people doing it like this?

Going into extension methods almost feels more like leaning towards creating a library or helper methods to support UI testing based on Appium.

As complexity grows I can definitely see how that might be more clean and convenient. But for the basic sample just to show people how to get set up and run their tests I tried to keep things as simple as possible.

**Comment by jfversluis** [comment]
Finished sample is now available here: https://learn.microsoft.com/samples/dotnet/maui-samples/uitest-appium-nunit/
