### ISSUE TITLE
The Maui app does not start on its own and needs to be triggered manually. It also needs to stay open because it does not restart

### ISSUE THREAD

**Issue by mdelgadov** [jfversluis/BasicAppiumSample#5]
Hi Gerald:

This great repo automatically starts the maui app when the tests start and it restarts the app properly every new test... 

But in a complex app this is not happening. 

Another  incompatibility was that I need use the path to the app instead of the name: app/bin/net8,.../android/...apk instead of com.company.app_xxx!App

1 Do you think this may be related? 

2 Any idea if the size of an app can affect the starting of it?

**Comment by jfversluis** [comment]
I will need to have more details to say something useful, but this all worked for me with what is in this repo. Actually I forgot about this one. The one that is more maintained and more official is here: https://github.com/dotnet/maui-samples/tree/main/8.0/UITesting/BasicAppiumNunitSample
